[package]
name = "glimmer_weave"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
libm = { version = "0.2", default-features = false }

[dev-dependencies]

[lib]
name = "glimmer_weave"
path = "src/lib.rs"
